# These values are what the IDP will update on each deploy.
# image.repository + image.tag together form the full image name.
image:
  repository: nginx
  tag: latest

replicaCount: 4

service:
  port: 80
